name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ${{ matrix.os }}
    environment: Production
    timeout-minutes: 240
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies with fallback
        run: |
          echo "Attempting installation with Bun..."
          if bun install --frozen-lockfile; then
            echo "Bun installation successful"
            echo "package_manager=bun" >> $GITHUB_ENV
          else
            echo "Bun installation failed, falling back to npm..."
            # Clean up any partial bun installs
            rm -rf node_modules
            # Use npm instead
            npm install
            if [ $? -eq 0 ]; then
              echo "npm installation successful"
              echo "package_manager=npm" >> $GITHUB_ENV
            else
              echo "Both Bun and npm installations failed"
              exit 1
            fi
          fi
        shell: bash

      # Install required dependencies for Linux builds
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-0 libwebkit2gtk-4.1-0 libgbm1

      # Setup macOS signing
      - name: Install Apple codesigning certificates
        if: matrix.os == 'macos-latest'
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CSC_LINK }}
          P12_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      # Platform-specific builds
      - name: Build and Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          SKIP_NOTARIZE: ${{ secrets.SKIP_NOTARIZE }}
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            if [ "$package_manager" = "bun" ]; then
              bun run build:win
            else
              npm run build:win
            fi
          elif [ "$RUNNER_OS" == "macOS" ]; then
            if [ "$package_manager" = "bun" ]; then
              bun run build:mac
            else
              npm run build:mac
            fi
          else
            if [ "$package_manager" = "bun" ]; then
              bun run build:linux
            else
              npm run build:linux
            fi
          fi
        shell: bash

      # Cleanup keychain
      - name: Clean up keychain
        if: matrix.os == 'macos-latest' && always()
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
